spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ens-auth-db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  key: "wNNzWV9GkJQ6OJtWtAZ0umC032DqYYQ2mvBHl3mdjmYA9e8Scr/QWJqRCSvWK0vn"